title: Another Redis Desktop Manager
description: A faster, better and more stable redis desktop manager [GUI client], compatible with Linux, Windows, Mac. What's more, it won't crash when loading massive keys.
show_downloads: false
google_analytics: G-3YCG7YS3BM
theme: jekyll-theme-cayman
github:
  gp_repository_url: https://github.com/qishibo/goanother
  repository_url: https://github.com/qishibo/AnotherRedisDesktopManager
plugins:
  - jekyll-sitemap
